Repository espressif/esp-protocols, pull requests merged in 2023-02, with the labels that each got.

#218 Add task_name config option (for websocket client) (IDFGH-9346)
  components/esp_websocket_client/esp_websocket_client.c
  components/esp_websocket_client/include/esp_websocket_client.h
Labels: Status: Opened

#222 components/mdns: use semaphore instead of task notification bits (IDFGH-9380) (IDFGH-9388)
  components/mdns/mdns.c
  components/mdns/private_include/mdns_private.h
Labels: Status: Opened

#223 Unite all tags under common structure (IDFGH-9399)
  components/esp_websocket_client/esp_websocket_client.c
  components/esp_websocket_client/examples/main/websocket_example.c
  components/esp_websocket_client/examples/pytest_websocket.py
  components/mdns/mdns.c
  components/mdns/mdns_networking_lwip.c
  components/mdns/mdns_networking_socket.c
  components/mdns/tests/test_apps/main/main.c
  components/mdns/tests/test_apps/main/mdns_test.c
Labels: Status: In Progress

#231 esp_modem: Return true from on_data callback in data mode
  components/esp_modem/idf_component.yml
  components/esp_modem/src/esp_modem_netif.cpp
  components/esp_modem/src/esp_modem_netif_linux.cpp
  components/esp_modem/src/esp_modem_uart.cpp
Labels: bug
